try {
  
  console.log("Begin try block");

  // no errors
  
  console.log("End try block");

} catch (err) {
  
  console.log("This won't run.");

}
